### ISSUE TITLE
Archived pages such as http://www.w124.co.uk/carsforsale.php?page=detail&id=200782 not recognisably archived

### ISSUE THREAD

**Issue by grahamperrin** [VerifiedJoseph/Save-to-the-Wayback-Machine#99]
<http://www.w124.co.uk/carsforsale.php?page=detail&id=200782> (and other car pages linked from <http://www.w124.co.uk/carsforsale.php>) are shown as not archived but truly, they **are** archived, e.g. https://web.archive.org/web/*/http://www.w124.co.uk/carsforsale.php?page=detail&id=200782

Possible to fix?

TIA

**Comment by VerifiedJoseph** [comment]
Thanks for reporting this. 

The page URL `http://www.w124.co.uk/carsforsale.php?page=detail&id=200782` is submit to the Wayback Availability API as `https://archive.org/wayback/available?url=http://www.w124.co.uk/carsforsale.php?page=detail&id=200782` because the URL parameter is not encoded the API thinks its checking the availability of `http://www.w124.co.uk/carsforsale.php?page=detail`, therefore no results are returned.

Pull request #100 should fix this bug. I'll test it some more and push out an update later this week.

**Comment by VerifiedJoseph** [comment]
Released version 5.3.4 which the fix from #100. This bug should now be fixed.

**Comment by grahamperrin** [comment]
Thanks! 

Incidentally, what's difference between 5.3.4 and 5.3.4.1?

**Comment by grahamperrin** [comment]
Fix verified (5.3.4.1). Thank you!
